### ISSUE TITLE
Chain upgrade trial testnet (internal)

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nyxd#28]
Once we have nxyd upgrade versions prepared (see issue#27), we should make a copy of sandbox and try upgrading it step by step from the current v0.26.1 all the way to 0.31.0, testing it all the way along to make sure everything stays functional.

**Comment by jstuczyn** [comment]
As we internally discussed in the office, when performing this trial run, it's going to be crucial we set up some IBC channels beforehand so we could see how the migration affects those.
